// import './root.scss'
import './pointer.scss'
import './layout.scss'
import './spacing.scss'
import './border.scss'
import './typography.scss'
import './tag.scss'
import './link.scss'
import './animation.scss'
import './background.scss'
import './box-shadow.scss'
